### ISSUE TITLE
Is it possible to build docker with app?

### ISSUE THREAD

**Issue by b1f17773** [formio/formio#1392]
Hello Guys,
i would like to know is it possible to build docker formio with app which will allow external users to use my forms?
I can log in as admin and create forms with access for everyone, but i don't know how to give access to forms.

I saw that it's possible with building manual formio, but i need this with docker. Is it possible?

**Comment by multinerd** [comment]
Yes, it is possible. 


```yaml
version: '3.7'

networks:
  db_mongodb_network:
    name: db_mongodb_network
  formio_network:
    name: formio_network
    
services:
  formio_web:
    build: D:/docker-data/formio-data/formio/
    container_name: formio_web
    restart: unless-stopped 
    ports:
      - "10310:3001"
    # The application wants to download things to the local directory
    # TODO: really wish I could mount this as read-only
    volumes:
      - D:/docker-data/formio-data/formio:/app:rw
    environment:
      DEBUG: "formio:*"
      NODE_CONFIG: '{"mongo": "mongodbconnectionstring", "domain": "https://formio.mysite.com", "email": { "type": "smtp" }, "settings": { "email": {"smtp": {"host": "emailhost.com", "port": 587, "secure": false, "ignoreTLS": false, "auth": { "user": "username@email.com", "pass": "password!" }, "allowUnauthorizedCerts": true } } } }'
      ROOT_EMAIL: "username"
      ROOT_PASSWORD: "password!"
    networks:
      - db_mongodb_network
      - formio_network
    stdin_open: true  # -i
    tty: true         # -t

```

The most impoartant thing here is this line

```
    volumes:
      - D:/docker-data/formio-data/formio:/app:rw
```

Im telling it that this repository is here `D:/docker-data/formio-data/formio` and to map it to `/app` in my container.

Steps to get up and running: 
- Clone the repository
- run yarn/npm
- docker compose up -d

I've been meaning to create an image where the repository is pre-downloaded but time is never on my side.

Let me know if you have any questions
